input_serial_number_class = "form-control"
get_info_button_css = ".btn.btn-primary.btn-block.btn--icon.btn--arrow"
field_validation_error_class = "field-validation-error"
serial_result_class = "c-bb-tile"
result_des_class = "c-result-tile__dl"
